require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'JobFinder' do
  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-fingerprint-scanner', :path => '../node_modules/react-native-fingerprint-scanner'

  pod 'react-native-biometrics', :path => '../node_modules/react-native-biometrics'

  target 'JobFinderTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.75.1' })
  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)
  end
end