const Images = {
  appLogo: require('./logo.png'),
  accountActive: require('./img/account-active.png'),
  account: require('./img/account.png'),
  applicationActive: require('./img/application-active.png'),
  application: require('./img/application.png'),
  arrowLeft: require('./img/arrow-left.png'),
  arrowRight: require('./img/arrow-right.png'),
  blibli: require('./img/blibli.png'),
  bookmarkActive: require('./img/bookmark-active.png'),
  bookmark: require('./img/bookmark.png'),
  bukalapak: require('./img/bukalapak.png'),
  calendar: require('./img/calendar.png'),
  delete: require('./img/delete.png'),
  dribble: require('./img/dribble.png'),
  edit: require('./img/edit.png'),
  empty1: require('./img/empty1.png'),
  empty2: require('./img/empty2.png'),
  flag: require('./img/flag.png'),
  glints: require('./img/glints.png'),
  gojek: require('./img/gojek.png'),
  google: require('./img/google.png'),
  homeActive: require('./img/home-active.png'),
  home: require('./img/home.png'),
  linkedin: require('./img/linkedin.png'),
  lock: require('./img/lock.png'),
  message: require('./img/message.png'),
  notification: require('./img/notification.png'),
  profile: require('./img/profile.png'),
  search: require('./img/search.png'),
  shopee: require('./img/shopee.png'),
  success: require('./img/success.png'),
  time: require('./img/time.png'),
  welcome: require('./img/welcome.png'),
  work: require('./img/work.png'),
  document: require('./img/document.png'),
  close: require('./img/close.png'),
  location: require('./img/location.png'),
  fingerPrint: require('./img/finger-print.png'),
}

export default Images
